/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const RoomScreenLazyImport = createFileRoute('/$room/screen')()
const RoomProducerLazyImport = createFileRoute('/$room/producer')()
const RoomHostLazyImport = createFileRoute('/$room/host')()
const RoomContestantRightLazyImport = createFileRoute(
  '/$room/contestant/right',
)()
const RoomContestantLeftLazyImport = createFileRoute('/$room/contestant/left')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RoomScreenLazyRoute = RoomScreenLazyImport.update({
  id: '/$room/screen',
  path: '/$room/screen',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$room/screen.lazy').then((d) => d.Route))

const RoomProducerLazyRoute = RoomProducerLazyImport.update({
  id: '/$room/producer',
  path: '/$room/producer',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$room/producer.lazy').then((d) => d.Route),
)

const RoomHostLazyRoute = RoomHostLazyImport.update({
  id: '/$room/host',
  path: '/$room/host',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$room/host.lazy').then((d) => d.Route))

const RoomContestantRightLazyRoute = RoomContestantRightLazyImport.update({
  id: '/$room/contestant/right',
  path: '/$room/contestant/right',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$room/contestant/right.lazy').then((d) => d.Route),
)

const RoomContestantLeftLazyRoute = RoomContestantLeftLazyImport.update({
  id: '/$room/contestant/left',
  path: '/$room/contestant/left',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$room/contestant/left.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$room/host': {
      id: '/$room/host'
      path: '/$room/host'
      fullPath: '/$room/host'
      preLoaderRoute: typeof RoomHostLazyImport
      parentRoute: typeof rootRoute
    }
    '/$room/producer': {
      id: '/$room/producer'
      path: '/$room/producer'
      fullPath: '/$room/producer'
      preLoaderRoute: typeof RoomProducerLazyImport
      parentRoute: typeof rootRoute
    }
    '/$room/screen': {
      id: '/$room/screen'
      path: '/$room/screen'
      fullPath: '/$room/screen'
      preLoaderRoute: typeof RoomScreenLazyImport
      parentRoute: typeof rootRoute
    }
    '/$room/contestant/left': {
      id: '/$room/contestant/left'
      path: '/$room/contestant/left'
      fullPath: '/$room/contestant/left'
      preLoaderRoute: typeof RoomContestantLeftLazyImport
      parentRoute: typeof rootRoute
    }
    '/$room/contestant/right': {
      id: '/$room/contestant/right'
      path: '/$room/contestant/right'
      fullPath: '/$room/contestant/right'
      preLoaderRoute: typeof RoomContestantRightLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$room/host': typeof RoomHostLazyRoute
  '/$room/producer': typeof RoomProducerLazyRoute
  '/$room/screen': typeof RoomScreenLazyRoute
  '/$room/contestant/left': typeof RoomContestantLeftLazyRoute
  '/$room/contestant/right': typeof RoomContestantRightLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$room/host': typeof RoomHostLazyRoute
  '/$room/producer': typeof RoomProducerLazyRoute
  '/$room/screen': typeof RoomScreenLazyRoute
  '/$room/contestant/left': typeof RoomContestantLeftLazyRoute
  '/$room/contestant/right': typeof RoomContestantRightLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$room/host': typeof RoomHostLazyRoute
  '/$room/producer': typeof RoomProducerLazyRoute
  '/$room/screen': typeof RoomScreenLazyRoute
  '/$room/contestant/left': typeof RoomContestantLeftLazyRoute
  '/$room/contestant/right': typeof RoomContestantRightLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$room/host'
    | '/$room/producer'
    | '/$room/screen'
    | '/$room/contestant/left'
    | '/$room/contestant/right'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$room/host'
    | '/$room/producer'
    | '/$room/screen'
    | '/$room/contestant/left'
    | '/$room/contestant/right'
  id:
    | '__root__'
    | '/'
    | '/$room/host'
    | '/$room/producer'
    | '/$room/screen'
    | '/$room/contestant/left'
    | '/$room/contestant/right'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RoomHostLazyRoute: typeof RoomHostLazyRoute
  RoomProducerLazyRoute: typeof RoomProducerLazyRoute
  RoomScreenLazyRoute: typeof RoomScreenLazyRoute
  RoomContestantLeftLazyRoute: typeof RoomContestantLeftLazyRoute
  RoomContestantRightLazyRoute: typeof RoomContestantRightLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RoomHostLazyRoute: RoomHostLazyRoute,
  RoomProducerLazyRoute: RoomProducerLazyRoute,
  RoomScreenLazyRoute: RoomScreenLazyRoute,
  RoomContestantLeftLazyRoute: RoomContestantLeftLazyRoute,
  RoomContestantRightLazyRoute: RoomContestantRightLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$room/host",
        "/$room/producer",
        "/$room/screen",
        "/$room/contestant/left",
        "/$room/contestant/right"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$room/host": {
      "filePath": "$room/host.lazy.tsx"
    },
    "/$room/producer": {
      "filePath": "$room/producer.lazy.tsx"
    },
    "/$room/screen": {
      "filePath": "$room/screen.lazy.tsx"
    },
    "/$room/contestant/left": {
      "filePath": "$room/contestant/left.lazy.tsx"
    },
    "/$room/contestant/right": {
      "filePath": "$room/contestant/right.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
